### ISSUE TITLE
[歌词提交/修正] 王以太, 刘至佳 - 危险派对

### ISSUE THREAD

**Issue by Seayay** [Steve-xmh/amll-ttml-db#1116]
### TTML 歌词文件下载直链

https://dpaste.org/w6Sg7/raw

### 提交缘由

新歌词提交

### 备注

从 Apple Music 逐字歌词导入 (id: 1594954369)

**Comment by Steve-xmh** [comment]
感谢你的大量歌词贡献！

按照审核员们的一致意见，我们想诚邀您参与成为歌词审核员，一同维护歌词和审核！
如有意愿，请电邮至 [stevexmh@qq.com](mailto:stevexmh@qq.com)，并留下您的 QQ 号码与所有审核员联系即可！
（为了避免邮件被送至垃圾箱，请顺便在本议题下回复您使用的电子邮件地址（本议题会暂时解锁），非常感谢！）

期待你的加入！

**Comment by Seayay** [comment]
> 感谢你的大量歌词贡献！
> 
> 按照审核员们的一致意见，我们想诚邀您参与成为歌词审核员，一同维护歌词和审核！
> 如有意愿，请电邮至 [stevexmh@qq.com](mailto:stevexmh@qq.com)，并留下您的 QQ 号码（或其他联系方式）与所有审核员联系即可！
> （为了避免邮件被送至垃圾箱，请顺便在本议题下回复您使用的电子邮件地址（本议题会暂时解锁），非常感谢！）
> 
> 期待你的加入！

siyaofang@126.com
