### ISSUE TITLE
[功能增强]一种新的 TTML 歌词下载方法 

### ISSUE THREAD

**Issue by chengnan049** [Steve-xmh/amll-ttml-db#1282]
### 歌曲名称

无 - 无

### 音乐对应的音乐平台和音乐 ID

12345678

### 其他备注

- [X] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

https://github.com/glomatico/gamdl 该工具可以从 Apple Music 获取 TTML，不过会面临 DMCA 问题

**Comment by Seayay** [comment]
很抱歉，您的 Issue 与本仓库无关，建议您移步至 [Steve-xmh/amll-ttml-tool](https://github.com/Steve-xmh/amll-ttml-tool)，将对此 Issue 做关闭处理。

**Comment by EnchStudio** [comment]
_难绷功能增强（_
