### ISSUE TITLE
[歌词请愿] ASMRZ - 잘자요 아가씨 (Prod. 과나)

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/amll-ttml-db#1312]
### 歌曲名称

ASMRZ - 잘자요 아가씨 (Prod. 과나)

### 音乐对应的音乐平台和音乐 ID

2129984063

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

可参考此视频以确认对唱关系：https://www.bilibili.com/video/av1954542898/

**Comment by ITManCHINA** [comment]
- #1492
