### ISSUE TITLE
[歌词提交/修正] Bad Bunny - MONACO

### ISSUE THREAD

**Issue by a23bc** [Steve-xmh/amll-ttml-db#1374]
### TTML 歌词文件下载直链

https://dpaste.org/ue9YT/raw

### 提交缘由

新歌词提交

**Comment by Xionghaizi001** [comment]
你好，如果你想提交一份新的投稿，请在提交issue后等待机器人自动检查通过即可进入人工审核流程，无需进行其他操作。
