### ISSUE TITLE
[歌词提交] 中国话 - S.H.E

### ISSUE THREAD

**Issue by Super12138** [Steve-xmh/amll-ttml-db#1535]
### TTML 歌词文件下载直链

https://raw.githubusercontent.com/Super12138/public-resources/main/%E4%B8%AD%E5%9B%BD%E8%AF%9D%20-%20S.H.E.ttml

### 提交缘由

新歌词提交

### 备注

网易云：[前往](https://music.163.com/#/song?id=375085)

**Comment by Xionghaizi001** [comment]
dpaste似乎已经恢复访问了，请尝试使用[TTML制作工具](https://steve-xmh.github.io/amll-ttml-tool/)进行提交。
