### ISSUE TITLE
[歌词请愿] 阿云嘎, HOYO-MiX - Regression

### ISSUE THREAD

**Issue by ITManCHINA** [Steve-xmh/amll-ttml-db#1797]
### 歌曲名称

阿云嘎, HOYO-MiX - Regression

### 音乐对应的音乐平台和音乐 ID

[1913478990](https://music.163.com/#/song?id=1913478990)

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

没有人做这首的话我就上传了哦😋

**Comment by Xionghaizi001** [comment]
平台自带的我看着质量还行啊😂除了没有排好版之外😂

**Comment by ITManCHINA** [comment]
> 平台自带的我看着质量还行啊😂除了没有排好版之外😂

是的，因为排版所以我宁愿自己再手打一份（？）😂

**Comment by Xionghaizi001** [comment]
> 是的，因为排版所以我宁愿自己再手打一份（？）😂

直接拿下来排一下版不就行了（

**Comment by ITManCHINA** [comment]
> 直接拿下来排一下版不就行了（

还要加一些背景人声吧，这两天看看啥情况吧🥲

**Comment by ITManCHINA** [comment]
#1857 Refered.

---

主教的爱，太沉重了...
