### ISSUE TITLE
[歌词提交/修正] 高橋未奈美, 佐倉綾音 - 明日への扉

### ISSUE THREAD

**Issue by Xionghaizi001** [Steve-xmh/amll-ttml-db#1854]
### TTML 歌词文件下载直链

https://dpaste.org/6Q5wc/raw

### 提交缘由

新歌词提交

### 备注

- 对 #1399 的一点修正。（Thanks to @ITManCHINA ）

**Comment by ITManCHINA** [comment]
好快的补🥲
