### ISSUE TITLE
[疑问] 关于歌词格式的「不要留空行」的硬性要求

### ISSUE THREAD

**Issue by dumbbird** [Steve-xmh/amll-ttml-db#2091]
### 歌曲名称

General enquiry

### 音乐对应的音乐平台和音乐 ID

N.A.

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

您好，偶然发现了这个项目并很感兴趣。只是，看过readme中的歌词硬性要求之后，产生了一个疑问。

关于「不要留空行，请善用结束时间来让歌词播放器自动生成间奏区域」这一条，对于逐字/逐词格式的歌词，是可能做到的，也能理解设置这一条要求的逻辑。

但是，对于传统的逐行格式的 .lrc 歌词，如果通篇歌词不留空行，此格式是无法识别出间奏区域的啊。

本人是一个传统LRC逐行歌词的爱好者，也有制作相关歌词十多年的经验。我只是有点好奇，在LRC格式不留空行的要求，是否真的合乎情理？

Thanks for sharing any insights in advance!

**Comment by Steve-xmh** [comment]
歌词库只允许提交TTML歌词，而TTML格式同样允许以行来打轴（在歌词编辑器中直接在一个单词里写入一行的歌词即可），为歌词行直接记录每行的始末时间。
不过你确实提醒了一些，目前GitHub机器人不能根据TTML生成带空行结束时间的逐行歌词文件，这个后面会补上。
