### ISSUE TITLE
[歌词请愿] YOASOBI - たぶん

### ISSUE THREAD

**Issue by ITManCHINA** [Steve-xmh/amll-ttml-db#2360]
### 歌曲名称

YOASOBI - たぶん

### 音乐对应的音乐平台和音乐 ID

1459343252

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

**Comment by Xionghaizi001** [comment]
24/11/16：已加入 waitlist 。

**Comment by Xionghaizi001** [comment]
#2997

**Comment by ITManCHINA** [comment]
好耶<img src="https://upload-bbs.mihoyo.com/upload/2022/11/14/4b4fb49d4bd402c530600e758ebb06bd_5477506439621383475.png" alt="阿姬开心" width="75" >
