### ISSUE TITLE
[歌词提交/修正] ギターと孤独と蒼い惑星

### ISSUE THREAD

**Issue by Doushabo** [Steve-xmh/amll-ttml-db#27]
### 歌曲名称

ギターと孤独と蒼い惑星

### 音乐对应的网易云音乐 ID

1991012773

### TTML 歌词文件下载直链

https://dpaste.org/gh1nZ/raw

### 提交缘由

新歌词提交

### 备注

添加 結束バンド-ギターと孤独と蒼い惑星 的歌词

**Comment by Steve-xmh** [comment]
“何かが変わって見えた ような”
这一句的 “見” 开始时间比结束时间晚了，请修正
