### ISSUE TITLE
[歌词请愿] 陈奕迅 - 这样很好 (Isha's Song)

### ISSUE THREAD

**Issue by OnismIS** [Steve-xmh/amll-ttml-db#2790]
### 歌曲名称

陈奕迅 - 这样很好 (Isha's Song)

### 音乐对应的音乐平台和音乐 ID

网易云音乐2643800682

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

**Comment by Xionghaizi001** [comment]
#2806 已进入审核流程。
