### ISSUE TITLE
[歌词提交/修正] The Weekend / JENNIE / Lily-Rose Depp - One Of The Girls

### ISSUE THREAD

**Issue by SteamFinder** [Steve-xmh/amll-ttml-db#307]
### 歌曲名称

The Weekend / JENNIE / Lily-Rose Depp - One Of The Girls

### 音乐对应的网易云音乐 ID

2058139099, 2106654726, 2106654728, 2106654727, 2087435418, 2106654171

### TTML 歌词文件下载直链

https://dpaste.org/wsqSO/raw

### 提交缘由

新歌词提交

### 备注

满足需求 歌词请愿#306

**Comment by Y-CIAO** [comment]
该歌曲歌词已经审核通过。
