### ISSUE TITLE
[歌词请愿] ピノキオピー,初音ミク (, Ado) - 神っぽいな

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/amll-ttml-db#448]
### 歌曲名称

ピノキオピー,初音ミク (, Ado) - 神っぽいな

### 音乐对应的网易云音乐 ID

1878313261,2108138514

### 其他备注

- [x] 这个歌曲在 Apple Music 上有逐词歌词

**Comment by EnchStudio** [comment]
我来解决翻译和音译
