### ISSUE TITLE
[歌词提交/修正] 初音ミク, 鏡音リン, GUMI, れるりり - 神のまにまに

### ISSUE THREAD

**Issue by Havenmab** [Steve-xmh/amll-ttml-db#616]
### TTML 歌词文件下载直链

https://dpaste.org/NdHv2/raw

### 提交缘由

修正已有歌词

### 备注

数据库歌词结构迁移后，我打的所有歌曲翻译歌词、音译歌词、背景人声设置都没了（对唱还是有的）。
这回重新打了这首歌曲的歌词，时间轴对得更准了，并添加了对唱歌词。

**Comment by Steve-xmh** [comment]
> ### TTML 歌词文件下载直链
> https://dpaste.org/NdHv2/raw
> 
> ### 提交缘由
> 修正已有歌词
> 
> ### 备注
> 数据库歌词结构迁移后，我打的所有歌曲翻译歌词、音译歌词、背景人声设置都没了（对唱还是有的）。 这回重新打了这首歌曲的歌词，时间轴对得更准了，并添加了对唱歌词。

已重新推送了迁移前的歌词数据，翻译音译应该都补充回来了，带来不便非常抱歉！
