### ISSUE TITLE
[歌词请愿] Travis Scott - STOP TRYING TO BE GOD

### ISSUE THREAD

**Issue by Eplorr** [Steve-xmh/amll-ttml-db#634]
### 歌曲名称

Travis Scott - STOP TRYING TO BE GOD

### 音乐对应的音乐平台和音乐 ID

1298432430

### 其他备注

- [x] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

https://music.apple.com/cn/album/astroworld/1421241217

**Comment by EnchStudio** [comment]
已完成的工作。

**Comment by SteamFinder** [comment]
已完成，本issue关闭。
