### ISSUE TITLE
[歌词请愿] NOMA - Brain Power (Long Version)

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/amll-ttml-db#803]
### 歌曲名称

NOMA - Brain Power (Long Version)

### 音乐对应的音乐平台和音乐 ID

1314989452

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

### 备注

O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-oooooooooooo AAE-O-A-A-U-U-A- O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-ooo-ooo-oooo EEEEO-A-AAA-AAA- O----------

**Comment by Seayay** [comment]
草

**Comment by EnchStudio** [comment]
草
