### ISSUE TITLE
[歌词提交/修正] 花玲/喵☆酱/宴宁/kinsen - 让风告诉你

### ISSUE THREAD

**Issue by Ironer03** [Steve-xmh/amll-ttml-db#808]
### TTML 歌词文件下载直链

https://dpaste.org/k2BT3/raw

### 提交缘由

新歌词提交

**Comment by Steve-xmh** [comment]
由于触发 Github 请求限制，自动审核没有成功，烦请重新提交，带来不便还请谅解！
