### ISSUE TITLE
[歌词提交/修正] Bruno Mars、Anderson .Paak、Silk Sonic - Leave The Door Open

### ISSUE THREAD

**Issue by Y-CIAO** [Steve-xmh/amll-ttml-db#83]
### 歌曲名称

Bruno Mars、Anderson .Paak、Silk Sonic - Leave The Door Open

### 音乐对应的网易云音乐 ID

1824927085

### TTML 歌词文件下载直链

https://dpaste.org/v6Vdz/raw

### 提交缘由

新歌词提交

### 备注

对唱、背景人声

**Comment by Steve-xmh** [comment]
因为大佬贡献了很多歌曲的歌词，所以想邀请大佬来成为协作者来协助审核歌曲，如果有意愿的话可以发送你的QQ号码邮件到我的邮箱里相互加一下好友：stevexmh@qq.com
