### ISSUE TITLE
[歌词请愿] 战双帕弥什,多多poi,JUSF周存,丁培峰 - 盘旋

### ISSUE THREAD

**Issue by Steve-xmh** [Steve-xmh/amll-ttml-db#840]
### 歌曲名称

战双帕弥什,多多poi,JUSF周存,丁培峰 - 盘旋

### 音乐对应的音乐平台和音乐 ID

NCM:1882049780,NCM:1882049407

### 其他备注

- [ ] 这个歌曲在 Apple Music 上有逐词歌词

**Comment by Seayay** [comment]
#1054
